model_config:
  model_path: "model/weights/ResNet_20241206_070301_best.h5"
  class_dict:
    0: "afghan"
    1: "chinese"
    2: "indian"
    3: "modern"
    4: "moroccan"
    5: "persian"
    6: "turkish"